=== miscounting/RewardBotJ/src/main/resources/out/config.schema.json
{"$id":"rewardbotj.config.schema.json","$schema":"http://json-schema.org/draft-07/schema#","title":"Configuration","type":"object","required":["channel","oauth","commands"],"properties":{"channel":{"type":"string","description":"The streamer's channel"},"bot_name":{"type":"string","description":"The Twitch bot account"},"oauth":{"type":"string","description":"OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)"},"commands":{"type":"array","items":{"$ref":"#/definitions/command"}}},"definitions":{"command":{"title":"Command","type":"object","required":["twitchRewardId","action"],"properties":{"optionalName":{"type":"string","description":"The name of this command. Optional - used mostly for debugging."},"twitchRewardId":{"type":"string","description":"Twitch-generated identifier for your custom channel points reward. You can find your reward ID here: https://www.instafluff.tv/TwitchCustomRewardID/?channel=yourchannel"},"action":{"$ref":"#/definitions/action"}}},"action":{"type":"object","title":"Action","properties":{"name":{"type":"string","description":"The name of this action; optional, for debugging."},"messageToWhisper":{"type":"string","description":"A message to whisper to your bot (if configured). Useful for triggering Streamlabs Chatbot commands."},"keysToPress":{"type":"string","description":" string to represent hotkeys. Must follow the Java KeyStroke format:\n      # See: https://docs.oracle.com/javase/7/docs/api/javax/swing/KeyStroke.html#getKeyStroke(java.lang.String)\n      # example: shift control alt command A"}}}}}

=== miscounting/RewardBotJ/src/main/resources/config.json
{
  "bot_name": "countabot",
  "channel": "miscounting",
  "oauth": "mySecretToken",
  "commands": [
    {
      "optionalName": "beard",
      "twitchRewardId": "d72c04c1-0c6e-4b83-ad06-e1abf1c2d6ca",
      "action": {
        "name": "beard filter",
        "keysToPress": "shift control alt meta 1"
      }
    },
    {
      "optionalName": "glam",
      "twitchRewardId": "c1b3575f-273e-4427-b999-82a587fa2c62",
      "action": {
        "keysToPress": "shift control alt meta 2"
      }
    },
    {
      "optionalName": "random unflattering filter",
      "twitchRewardId": "a4188288-eb26-42fb-a613-a25df345c950",
      "action": {
        "performAtRandom": [
          {
            "name": "spider",
            "keysToPress": "shift control alt meta A"
          },
          {
            "name": "fart sound",
            "messageToWhisper": "!farts"
          }
        ]
      }
    }
  ]
}
